### ISSUE TITLE
Fix calculations based on stratified period

### ISSUE THREAD

**Issue by lawinslow** [USGS-R/mda.lakes#79]
All of these are broken. I'm pretty sure its due to 
```
SthermoD_mean    
SmetaTopD_mean    
SmetaBotD_mean    
mean_epi_vol    
mean_hyp_vol    
mean_epi_hypo_ratio 
```

I'm pretty sure its due to the code [here](https://github.com/USGS-R/mda.lakes/blob/master/R/GLM.physics.R#L213-L234). But I'm not entirely sure.

**Comment by lawinslow** [comment]
@jread-usgs want to take a crack at this?

**Comment by lawinslow** [comment]
@jread-usgs Ignore this. I was wrong on my initial assessment. Super easy fix.

**Comment by jread-usgs** [comment]
:dancers:

**Comment by lawinslow** [comment]
Fixed
