### ISSUE TITLE
update populate_base_lake_nml to use get_latLon

### ISSUE THREAD

**Issue by wdwatkins** [USGS-R/mda.lakes#96]
Also set default for `nsave` to 1

**Comment by jread-usgs** [comment]
Looks like it calls both version of `get_latlon`, 
the newer version in the [function inputs](https://github.com/USGS-R/mda.lakes/blob/master/R/populate_base_lake_nml.R#L18) and the older version [later](https://github.com/USGS-R/mda.lakes/blob/master/R/populate_base_lake_nml.R#L97), which overrides it
